version: '3'

services:
  web_server:
    image: nginx:latest
    container_name: web_server
    volumes:
    - ./nginx_templates/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx_templates/html:/usr/share/nginx/html
    - ./empty_nginx_conf/:/etc/nginx/conf.d/  # Empty directory replaces default config
    ports:
    - "8080:80"
    networks:
      - app_network

  fuego:
    build: .
    container_name: fuego
    command: bash -c "gunicorn main:wsgi_app --bind 0.0.0.0:1111 & uvicorn main:asgi_app --host 0.0.0.0 --port 2222"
    ports:
      - "1111:1111"
      - "2222:2222"
    networks:
      - app_network

networks:
  app_network:
